package mostafa.qc.runners;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;

/**
 * ============================================================================
 * Failed Test Runner
 * ============================================================================
 * Description: Re-runs only failed scenarios from previous execution.
 * Uses the rerun.txt file generated by other runners.
 * Author: Mostafa QC
 *
 * Usage:
 *   - mvn test -Dtest=FailedTestRunner
 *   - Run after main test execution to retry failures
 * ============================================================================
 */
@CucumberOptions(
        // ========================================================================
        // RERUN FILE - Contains failed scenario paths
        // ========================================================================
        features = "@target/cucumber-reports/rerun.txt",

        glue = {"mostafa.qc.stepdefinitions"},

        plugin = {
                "pretty",
                "html:target/cucumber-reports/rerun/cucumber.html",
                "json:target/cucumber-reports/rerun/cucumber.json"
        },

        monochrome = true
)
public class FailedTestRunner extends AbstractTestNGCucumberTests {
    // No parallel execution for reruns - run sequentially for stability
}